### ISSUE TITLE
camel-case broken for CLJS

### ISSUE THREAD

**Issue by okal** [r0man/inflections-clj#11]
**Environment**
lein-cljsbuild Rhino REPL

**To reproduce**
1. Run `lein trampoline cljsbuild repl-rhino`
2. Enter `(require 'inflections.core)`
3. Enter `(inflections.core/camel-case "this-that")`

The result is "This-T-hat", rather than the expected "ThisThat". Is this known/intended behaviour?

**Comment by r0man** [comment]
Patch welcome!
