### ISSUE TITLE
Should CamelCase include Rubyisms?

### ISSUE THREAD

**Issue by jcf** [r0man/inflections-clj#18]
Hi @r0man,

I'm not sure replacing a slash with two colons makes sense in Clojure-land, and wondered what you think about it.

If we're porting ActiveSupport's implementation to Clojure perhaps it's sensible to follow their pattern of `clojure.core/name` ending up as `ClojureCore::Name`, but given how often qualified keywords show up in Clojure, and considering camelCase itself knows nothing about the Ruby module syntax perhaps we should stop adding `::`…

Let me know what you think. Maybe a quick survey of who uses the double-colon behaviour is in order before making any decisions.

Hope you are well,

James

**Comment by r0man** [comment]
@jcf Thanks, I'm fine. I don't think many people rely on this Rubyism. So I'm fine with bumping the version and removing it.
